name: Brooklyn Synergy
favicon: null
layout_spectrum: 0.87718
typography_spectrum: 0.7708
title: Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5dba8b'
    - '#ffffff'
    - '#202020'
    - '#126f40'
    - '#d3c0dc'
  brandStrength: 1
  lightness: 0.925463976804167
  saturation: 0.2681522585917264
  rhythmicContrast: 1
purpose: []
