name: Brooklyn Synergy
favicon: null
layout_spectrum: 0.1654085956979543
typography_spectrum: 0.30482033360749483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7620611276943237
  lightness: 0.925463976804167
  saturation: 0.2681522585917264
  rhythmicContrast: 0.8674957789480686
purpose: []
